[project]
name = "stat_rethinking_2026"
r_version = "4.5"

# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
# Example: { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
repositories = [
 { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
 { alias = "STAN", url = 'https://stan-dev.r-universe.dev'}
]

# A list of packages to install and any additional configuration
# Examples:
    # "dplyr",
    # {name = "dplyr", repository = "CRAN"},
    # {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
dependencies = [
    "devtools",
    "loo",
    "cmdstanr",
    { name = "rethinking", git = "https://github.com/rmcelreath/rethinking", branch = "slim" },
    "tidyverse",
    "tidybayes",
    "brms",
]
